export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  SOURCING = 'SOURCING',
  PREPARING = 'PREPARING',
  PACKAGING = 'PACKAGING',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
