export enum OrderStatus {
  DRAFT = 'DRAFT',
  PLACED = 'PLACED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  VOIDED = 'VOIDED',
  HELD = 'HELD',
  RECEIVED = 'RECEIVED',
  SOURCING = 'SOURCING',
  PACKAGING = 'PACKAGING',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
}
